export enum ECMSTypes {
  USEFUL_INFO = 'USEFUL_INFO',
  ABOUT_CONFERENCE = 'ABOUT_CONFERENCE',
  VISA_ON_ARRIVAL = 'VISA_ON_ARRIVAL',
  VISITORS_VISA = 'VISITORS_VISA',
  TRANSIT_VISA = 'TRANSIT_VISA',
  QA = 'QA',
  NEWS = 'NEWS',
  MEDIA = 'MEDIA',
  TRANSPORT_CAR_RENTALS = 'TRANSPORT_CAR_RENTALS',
  TRANSPORT_SHUTTLE_SERVICES = 'TRANSPORT_SHUTTLE_SERVICES',
  COMSEC = 'COMSEC',
	PRIVACY_POLICY = 'PRIVACY_POLICY',
	TOLL_NUMBER = 'TOLL_NUMBER'
}
