export enum ENotificationType {
  NEW_CHAT_NOC = 'NEW_CHAT_NOC',
  NEW_CHAT_PARTICIPANT = 'NEW_CHAT_PARTICIPANT',
  BOOKING_REQUEST = 'BOOKING_REQUEST',
  BOOKING_APPROVED = 'BOOKING_APPROVED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  BOOKING_ROOM_CHANGED = 'BOOKING_ROOM_CHANGED',
  BROADCAST_MESSAGE = 'BROADCAST_MESSAGE',
  COVID_RESULT = 'COVID_RESULT',
}
