export enum EQAtypes {
  VENUES_HOTEL_ACCESS = 'VENUES_HOTEL_ACCESS',
  MEDIA = 'MEDIA',
  ACCREDITATION = 'ACCREDITATION',
  TRANSPORT = 'TRANSPORT',
  ACCOMODATION = 'ACCOMODATION',
  SECURITY = 'SECURITY',
  TELECOM = 'TELECOM',
  OPENING_CEREMONY = 'OPENING_CEREMONY',
}
