export enum EUserRole {
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
  SPEAKER = 'SPEAKER',
  ATTENDEE = 'ATTENDEE',

  // START OF DEPRECATED ROLES
  COMMUNICATION_MANAGER = 'COMMUNICATION_MANAGER',
  VENUES_MANAGER = 'VENUES_MANAGER',
  TRANSPORT_MANAGER = 'TRANSPORT_MANAGER',
  CONTENT_MANAGER = 'CONTENT_MANAGER',
  FRONT_DESK = 'FRONT_DESK',
  // END OF DEPRECATED ROLES

  HOSPITALITY = 'HOSPITALITY',
  TRANSPORT = 'TRANSPORT',
  COMS = 'COMS',
  COMMAND_POST = 'COMMAND_POST',
}
