export enum EVenueType {
  EVENT_VENUE = 'EVENT_VENUE',
  HOTEL_APARTMENT_VENUE = 'HOTEL_APARTMENT_VENUE',
  RESTAURANT_VENUE = 'RESTAURANT_VENUE',
  BAR_VENUE = 'BAR_VENUE',
  NIGHT_CLUB_VENUE = 'NIGHT_CLUB_VENUE',
  COFFEE_SHOP_VENUE = 'COFFEE_SHOP_VENUE',
  MUSEUM_MEMORIAL_VENUE = 'MUSEUM_MEMORIAL_VENUE',
  NATIONAL_PARK = 'NATIONAL_PARK',
  ART_CRAFT = 'ART_CRAFT',
  SHOPPING_MALL = 'SHOPPING_MALL',
  OTHERS = 'OTHERS',
}
