export enum ENotificationType {
	BOOKING_APPROVED = 'BOOKING_APPROVED',
	BOOKING_CANCELLED = 'BOOKING_CANCELLED',
	BOOKING_REQUEST = 'BOOKING_REQUEST',
	BOOKING_ROOM_CHANGED = 'BOOKING_ROOM_CHANGED',
	NEW_CHAT_NOC = 'NEW_CHAT_NOC',
	NEW_CHAT_PARTICIPANT = 'NEW_CHAT_PARTICIPANT',
}