export enum EQAtypes {
	ACCOMODATION = 'ACCOMODATION',
	ACCREDITATION = 'ACCREDITATION',
	MEDIA = 'MEDIA',
	OPENING_CEREMONY = 'OPENING_CEREMONY',
	SECURITY = 'SECURITY',
	TELECOM = 'TELECOM',
	TRANSPORT = 'TRANSPORT',
	VENUES_HOTEL_ACCESS = 'VENUES_HOTEL_ACCESS'
}