export enum EUserRole {
  ADMIN = 'ADMIN',
  ATTENDEE = 'ATTENDEE',
  MODERATOR = 'MODERATOR',
  SPEAKER = 'SPEAKER',
  COMMAND_POST = 'COMMAND_POST',
  COMS = 'COMS',
  HOSPITALITY = 'HOSPITALITY',
  TRANSPORT = 'TRANSPORT',
}
